import type { Metadata } from "next"
import { Roboto_Condensed } from "next/font/google"
import "./globals.css"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter"
import Providers from "@/lib/Providers/Providers"
import { Toaster } from "sonner"

// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// })
//
// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// })

const geistRobotoCondensed = Roboto_Condensed({
	variable: "--font-roboto-condensed",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<Providers>
			<html lang="en">
				<body className={`${geistRobotoCondensed.variable} antialiased`}>
					<AppRouterCacheProvider>
						<>
							<Toaster position="top-center" />
							{children}
						</>
					</AppRouterCacheProvider>
				</body>
			</html>
		</Providers>
	)
}
